// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_USER_STRATAGEMS 6

extern void assignStratagems();
void updateStratagemSelection();
void _executeStdStratagem(uint8_t *sequence, char *path);
void _executeUserStratagem(uint8_t index);
void updatePresets();
void showMsgBox(char *msg);
void hideMsgBox();
void enableImageMode();
void disableImageMode();
void resolvePresetImages();
char *resolvePresetKey(char presetIndex, int8_t itemIndex);
void resetPresets();
void finalizeManualExecution();
void updateManualSequence();
void lookupManualSequence();
void resetCooldowns();
uint64_t getNow();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
